#################################################################
## Lighting Automations
#################################################################
- alias: Lights - Turn On Front Porch Light at Sunset

  trigger:
    - platform: sun
      event: 'sunset'
      offset: '-00:15:00'

#  condition:
#    - condition: state
#      entity_id: input_boolean.disable_exterior_on_sunset
#      state: 'off'

  action:
    - service: switch.turn_on
      entity_id: switch.front_porch

- alias: Lights - Turn Off Front Porch Light at Sunrise

  trigger:
    - platform: sun
      event: 'sunrise'

  action:
    - service: switch.turn_off
      entity_id: switch.front_porch

- alias: Lights - Turn On Breezeway Light at Sunset

  trigger:
    - platform: sun
      event: 'sunset'
      offset: '-00:15:00'

  action:
    - service: switch.turn_on
      entity_id: switch.breezeway

- alias: Lights - Turn Off Breezeway Light at 10:30 

  trigger:
    - platform: time
      at: '22:30'

  action:
    - service: switch.turn_off
      entity_id: switch.breezeway

- alias: Lights - Turn On Front Hall Light 5 minutes before Sunset if alarm is armed

  trigger:
   - platform: sun
     event: 'sunset'
     offset: '-00:05:00'
#    - platform: time
#      at: '15:14'

#  condition:
#    - condition: state
#      entity_id: alarm_control_panel.elkm1_area_001
#      state: 'armed'

  action:
    - service: switch.turn_on
      entity_id: switch.front_hall

- alias: Lights - Turn Off Front Hall Light at 10:05

  trigger:
    - platform: time
      at: '22:05'

  action:
    - service: switch.turn_off
      entity_id: switch.front_hall

- alias: Lights - Turn On Island Light at Sunset

  trigger:
    - platform: sun
      event: 'sunset'
      offset: '+00:00:00'

#  condition:
#    - condition: state
#      entity_id: alarm_control_panel.elkm1_area_001
#      state: 'armed'

  action:
    - service: light.turn_on
      entity_id: light.island 

- alias: Lights - Turn Off Island Light at 10:07

  trigger:
    - platform: time
      at: '22:07'

  action:
    - service: light.turn_off
      entity_id: light.island

